### ISSUE TITLE
Input Validation

### ISSUE THREAD

**Issue by Stivo** [webplatformz/challenge#10]
When my client adds another field to the outgoing messages, it is broadcasted with the additional field to other clients:

00:21:44.714 client-4 - sending { "type": "CHOOSE_CARD", "data": {"number":8,"color":"DIAMONDS","int":133} }
00:21:44.718 client-3 - received {"type":"PLAYED_CARDS","data":[{"number":8,"color":"DIAMONDS","int":133}]}

This could obviously used to cheat if a bot starts to use this.

**Comment by r3dDoX** [comment]
Yeah we're working on the validation part with Validation.js

**Comment by r3dDoX** [comment]
unnecessary properties should now be cleaned
