### ISSUE TITLE
bot skeleton for Javascript

### ISSUE THREAD

**Issue by stefanjaeger** [webplatformz/challenge#12]
Hi all
I'm totally new for this Jass challenge, but it looks promising and interesting to me. Is there a bot skeleton or even a real bot already in Javascript?

BR
Stefan

**Comment by r3dDoX** [comment]
Hey nice to see you here

Unfortunately the only thing close to a javascript bot is our integration test :)

Regards Patrick

**Comment by joachimprinzbach** [comment]
For all that are also interested: 

https://www.npmjs.com/package/javascript-jass-bot
