### ISSUE TITLE
Server should respond with REJECT_MESSAGE for illegal messages

### ISSUE THREAD

**Issue by adiherzog** [webplatformz/challenge#2]
If the server receives a message that is not valid, it should respond with REJECT_MESSAGE or similar.

**Comment by r3dDoX** [comment]
now you will get a BAD_MESSAGE for messages with the wrong type or not parseable JSON. But we don't check every property of the message payload. Which means it is still possible that a server error will be thrown, but no BAD_MESSAGE sent...

**Comment by r3dDoX** [comment]
We added the more detailed error handling on our trello board. I will close this issue for now
