### ISSUE TITLE
Layout of Cards on Table in Firefox is ugly

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#3]
Layout of Cards on the table in Firefox appears to be wrong:

![jasschallenge_karten_in_firefox](https://cloud.githubusercontent.com/assets/755721/8650900/41301f7a-2976-11e5-9184-38956907dc50.png)

the cards are too long, the lower ones are not well visible.

**Comment by r3dDoX** [comment]
Use Chrome :)

**Comment by r3dDoX** [comment]
The new UI should be rendered correctly and all modern browsers
