### ISSUE TITLE
Timeout for choosing a card is too short

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#4]
For demonstration purposes or for people just starting to learn how to "Jass" the current timeout of 1 minute for choosing a card is too short. Also for debugging purposes, it could be helpful to allow to have a session open for longer time.

I think you should allow to keep a session open for longer time without anyone making a move.
Proposal: allow for 10 minutes without interaction or even more.

**Comment by r3dDoX** [comment]
Yep, I think we have to make a distinction between bot and User...

**Comment by bruderol** [comment]
Very good idea! :smile:

**Comment by r3dDoX** [comment]
For now I added a ping mechanism which will ping your websocket every 30 seconds. If you use websockets in the browser or some sort of websocket library this ping request should most certainly be handled by the framework. This prevents your websockt form getting disconnected.

Later we may really implement a distinction for client/bot, but for now this should work.

**Comment by bruderol** [comment]
:+1:
