### ISSUE TITLE
Fix and improve Collecting Cards

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#41]
1. There is a bug in current collection of cards:
When other player made a stich, I still see the cards, but not in the correct order (my card is not in front of me)

2. The following behaviour is not optimal:
Seeing the text "collecting cards" (also when I did not make the Stich) gives me the impression, that I made the Stich and can take it now. I think that in the case where I did not make the Stich, it should be a different text, or even better no text and instead automatic taking of cards (see next point).

3. Proposal / Wish:
Since I can now see the last Stich allways (by clicking on the cards in upper left corner), it would be great if I had not allways to take the Stich manually, but it will be collected automatically after 2-5 seconds.

4. Nice to have, but might be important for manual players for the real Jass-Feeling:
Other players should get feedback (by collecting the cards in the UI) as soon as the manual player has taken the Stich (or with a delay of some seconds, to ensure that everybody had enough time to see it).

I think the optimal solution would be to implement point 4: taking when player takes, but with a minimal delay and only text "Collect cards" for player who won the Stich. Slower players can still see the old Stich by clicking on the collected cards.

**Comment by bruderol** [comment]
@dstucki @r3dDoX What do you think?

**Comment by r3dDoX** [comment]
We're currently working on some of the features you talk about. Will get back to this when we're finished

**Comment by r3dDoX** [comment]
We did remove the taking of the cards completely. There is a delay of 2 seconds until the cards get taken in. After that you have to click last stich to see it again

**Comment by bruderol** [comment]
:+1: :clap: :top: 
much better!
