### ISSUE TITLE
Make status of game visible

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#6]
Following things should be visualized:

1. What is trumpf (currently does not allways update properly or immediately)

2. Who has to choose trumpf 

      * Some marker behind player name
      * A message on the players window, when he has to choose trumpf!
      * the UI part for choosing trumpf should only be enabled, when the current player needs to choose trumpf

3. The points in total for each team (only updated at the end of each game)

4. If the game has finished because a team has won (and maybe the reason, in case a player was run into the timeout).

**Comment by r3dDoX** [comment]
We're working on the Trumpf part. The GUI to play has been designed to just manual test the game. By now it has evolved somehow and we will improve it to be a full fledged User Interface

**Comment by bruderol** [comment]
@r3dDoX you do not have to justify yourself.

I know that you are working on it and that it was first only designed for testing purpose.
But I am very impressed what is allready there, realy good work! Very cool! :smile: 

That is also why I think, that with little improvements we can make this platform fit for realy cool jasschallenge bot against human tournaments. 

I only wanted to give some input, what needs to be improved, such that we can make such a tournament.

Let me know if I can help somehow.

Thanks for all!

**Comment by r3dDoX** [comment]
with the new UI this should be solved

**Comment by bruderol** [comment]
Wow - many compliments! 
The new UI is just awesome!!!
Much much much better! Great!

Now everything is visualized, the usability is great! Almost perfect.

Just one minor observation (maybe just my personal opinion):
The highlighting of the player that started the last round (circle with dot inside) and the player that has to start the next round (or started the current round, which is highlighted by blue background) was not intuitive for me.
Especially I find it confusing, that the circle (who started the last round) stays still visible until the current round is finished (which confused me, because: why should somebody be interested in that information, after the first player has played the first card of the next round??). I was wondering what this circle means.

What I would have expected, is something like this:
blue = the player that has to play the next card (allways moving around, not only the first of the round)
circle = the player that started the round that is currently played or still lying on the table (and not the last one, before the one that is currently being played)

Maybe some additional explaining text (e.g. text "It's your turn!") could be helpful, because the visual markers are not self explaining.

But the rest of the UI seems to be just great!

**Comment by bruderol** [comment]
@r3dDoX please see my feedback above. Maybe open a new issue because of the non-intuitive "player in turn"- and "player that started"-markers?

**Comment by bruderol** [comment]
@r3dDoX Maybe I even missunderstood it again - after playing some more rounds, it seems to me that the circle-marker is not understandable to me. I do not get it, what this marker is telling me. all interpretations I found out so far, seem to fail again (or is this marker implemented wrong? Bug?)

**Comment by r3dDoX** [comment]
Yeah the marker isn't really intuitive. The icon with the circle and the dot means that this player chose the Trumpf, while the blue background marks the player who made the Stich and now has to play or already played the first card in this round...

I'll probably remove this icon and just leave the blue background which will move to the player who has to play a card...
