### ISSUE TITLE
Game destroyed after wrong user action

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#7]
If the user of the web application clicks something unexpected the game is destroyed. This should not happen.

**Example Scenario:**
1. user should choose trumpf (but he does not know this or did not realize that he has to choose from left part in the UI)
2. instead of chooisng trumpf, the user clicks on one of the cards to start playing (nothing happens, the log shows message "BAD_MESSAGE").
3. Now the user realizes, that he has to choose trumpf (which is currently not visible in UI) and chooses from left UI side.
4. The user now once again tried to play the card (Clubs/11 in this example), but the server does not react anymore. User can not continue to play, no reaction from server, after some time one of the teams wins.

see the following log:
Log:
CONNECTED

RESPONSE: {"type":"REQUEST_PLAYER_NAME"}

SENT: {"type":"CHOOSE_PLAYER_NAME","data":"rolf"}

RESPONSE: {"type":"REQUEST_SESSION_CHOICE","data":[]}

SENT: {"type":"CHOOSE_SESSION","data":{"sessionChoice":"CREATE_NEW","sessionName":"RolfTest"}}

RESPONSE: {"type":"BROADCAST_SESSION_JOINED","data":{"name":"rolf","id":0}}

RESPONSE: {"type":"BROADCAST_SESSION_JOINED","data":{"name":"rodolfo-43bcb8f1-54f1-4e40-a4d6-c2c9cfe6de56","id":1}}

RESPONSE: {"type":"BROADCAST_SESSION_JOINED","data":{"name":"rodolfo-4889229e-c915-4d0f-9e90-7e12fb3c5b1c","id":2}}

RESPONSE: {"type":"BROADCAST_SESSION_JOINED","data":{"name":"rodolfo-7d95be0b-e85e-45c7-92e9-46ba15eaf759","id":3}}

RESPONSE: {"type":"BROADCAST_TEAMS","data":[{"name":"Team 1","players":[{"name":"rolf","id":0},{"name":"rodolfo-4889229e-c915-4d0f-9e90-7e12fb3c5b1c","id":2}]},{"name":"Team 2","players":[{"name":"rodolfo-43bcb8f1-54f1-4e40-a4d6-c2c9cfe6de56","id":1},{"name":"rodolfo-7d95be0b-e85e-45c7-92e9-46ba15eaf759","id":3}]}]}

RESPONSE: {"type":"DEAL_CARDS","data":[{"number":14,"color":"CLUBS"},{"number":9,"color":"HEARTS"},{"number":11,"color":"CLUBS"},{"number":13,"color":"SPADES"},{"number":7,"color":"DIAMONDS"},{"number":10,"color":"CLUBS"},{"number":11,"color":"HEARTS"},{"number":13,"color":"DIAMONDS"},{"number":7,"color":"CLUBS"}]}

RESPONSE: {"type":"REQUEST_TRUMPF","data":false}

SENT: {"type":"CHOOSE_CARD","data":{"number":11,"color":"CLUBS"}}

RESPONSE: {"type":"BAD_MESSAGE","data":"{\"type\":\"CHOOSE_CARD\",\"data\":{\"number\":11,\"color\":\"CLUBS\"}}"}

SENT: {"type":"CHOOSE_TRUMPF","data":{"mode":"TRUMPF","trumpfColor":"CLUBS"}}

SENT: {"type":"CHOOSE_CARD","data":{"number":11,"color":"CLUBS"}}

SENT: {"type":"CHOOSE_CARD","data":{"number":11,"color":"CLUBS"}}

SENT: {"type":"CHOOSE_CARD","data":{"number":11,"color":"CLUBS"}}

SENT: {"type":"CHOOSE_TRUMPF","data":{"mode":"TRUMPF","trumpfColor":"CLUBS"}}

SENT: {"type":"CHOOSE_CARD","data":{"number":11,"color":"CLUBS"}}

SENT: {"type":"CHOOSE_CARD","data":{"number":11,"color":"CLUBS"}}

RESPONSE: {"type":"BROADCAST_WINNER_TEAM","data":{"name":"Team 2","points":0,"currentRoundPoints":0}}

RESPONSE: {"type":"BROADCAST_WINNER_TEAM","data":{"name":"Team 1","points":0,"currentRoundPoints":0}}

RESPONSE: {"type":"BROADCAST_WINNER_TEAM","data":{"name":"Team 1","points":0,"currentRoundPoints":0}}

DISCONNECTED

**Comment by r3dDoX** [comment]
We're still working on a solution for this. Since the online player is like any other bot there is little hope that after the wrong message, he can recover... But maybe we'll find a good solution for that. Any ideas?

**Comment by bruderol** [comment]
Idea: The UI has to be improved, such that unallowed messages are not sent!

**Comment by bruderol** [comment]
If you give me access, I might help a little to improve the UI.

**Comment by r3dDoX** [comment]
The new UI is more user centered and shouldn't allow any wrong action.
