### ISSUE TITLE
keep same corner for same player over multiple rounds

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#8]
As an online player, I not always have my card in the upper left corner (as in the first round), after the first round, I see my card in the lower left corner. 

I think the players should stay at the same position for the whole game.

This is confusing.

Proposal: Online player should allways have lower left corner on the table.

**Comment by r3dDoX** [comment]
At first we implemented the logic to always display the players card in the same place. i.e. the first player in the top left, second top right and so on. But unfortunately it gets a bit distracted in the second turn, but should work again afterwards... We're working on that

**Comment by r3dDoX** [comment]
Now the players should stay in the corner they start with the whole game. But the position you join the game will decide which corner you'll get

**Comment by bruderol** [comment]
Cool, thanks. :+1: 

But I think the manual player has to know / see somehow in which corner he is sitting and it must be clearly visible whether it is his turn or not yet (e.g. for when two humans play against 2 bots).

this is important if you want to use the paltform to make tournaments with multiple humans playing together or against bots. Just imagine how fun such human-bot-tournaments could be.

**Comment by r3dDoX** [comment]
With the new UI the player will always be on the same side
