### ISSUE TITLE
Bot-as-a-Service-Deployment-Environment

### ISSUE THREAD

**Issue by bruderol** [webplatformz/challenge#9]
Give users a platform where they can deploy bots of different technologies (or at least one technology) as a service.

Acceptance criterias:
 * User can deploy bots on this platform (register under a name)
 * Bots running on this platform can be choosen to play against them in the jasschallenge app.
 * The platform ensures that bots running on this platform can not communicate between each other (disallow any connections to the outside or between them, only connection to the jasschallenge app is allowed).

**Comment by r3dDoX** [comment]
Since we want to allow bots in all programming languages which are able to communicate over Websockets this is quite a big challenge. We would need something like Docker VMs in which you can upload your bot. Do you have any idea how to solve this?

**Comment by bruderol** [comment]
Might be solvable with Docker Images. But I agree, that this might be too hard to achieve.

**Comment by r3dDoX** [comment]
We solved this issue with our new jassbot registry where you can register your bot which then will be able to join any tournament on request
